# Generated by Django 3.0.1 on 2020-01-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='nextId',
            new_name='next_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='weekday',
        ),
    ]
