# Generated by Django 3.0.1 on 2020-01-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20200107_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='wednesday',
            field=models.BooleanField(default=True),
        ),
    ]
