# Generated by Django 3.0.1 on 2020-01-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistComplete',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrDate',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
