# Generated by Django 3.0.1 on 2020-01-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateTime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currdate',
            name='name',
        ),
        migrations.AlterField(
            model_name='currdate',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
