# Generated by Django 3.0.1 on 2020-01-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateTime', '0002_auto_20200111_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistcomplete',
            name='name',
        ),
        migrations.AddField(
            model_name='currdate',
            name='name',
            field=models.CharField(default='Checklist Date', max_length=300, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklistcomplete',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currdate',
            name='date',
            field=models.DateField(),
        ),
    ]
